allowBuilds:
  '@clerk/shared': true
  bufferutil: true
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@tailwindcss/oxide'
  - bufferutil
  - esbuild
  - sharp
  - unrs-resolver
